CREATE DATABASE osb_sp;

USE osb_sp;

CREATE TABLE R001TPR(
	CodTip INT NOT NULL,
	DesTip VARCHAR(10),
	PRIMARY KEY(CodTip)
);

CREATE TABLE R001PRO(
	CodPro INT NOT NULL,
	CodTip INT,
	NumPro INT,
	DatPro DATETIME,
	DesEme VARCHAR(500),
	PRIMARY KEY(CodPro),
	FOREIGN KEY(CodTip) REFERENCES R001TPR(CodTip)
);

CREATE TABLE R001PAR(
	CodPar INT NOT NULL,
	SigPar VARCHAR(10),
	DesPar VARCHAR(200),
	PRIMARY KEY(CodPar)
);

CREATE TABLE R001VER(
	CodVer INT NOT NULL,
	NomVer VARCHAR(50),
	PRIMARY KEY(CodVer)
);
CREATE TABLE R001VPA(
	CodVer INT NOT NULL,
	CodPar INT NOT NULL,
	DatIni DATETIME,
	DatFim DATETIME,
	PRIMARY KEY(CodVer, CodPar, DatIni),
	FOREIGN KEY(CodVer) REFERENCES R001VER(CodVer),
	FOREIGN KEY(CodPar) REFERENCES R001PAR(CodPar)
);

CREATE TABLE R001VPR(
	CodVer INT NOT NULL,
	CodPro INT NOT NULL,
	PRIMARY KEY(CodVer, CodPro),
	FOREIGN KEY(CodVer) REFERENCES R001VER(CodVer),
	FOREIGN KEY(CodPro) REFERENCES R001PRO(CodPro)
);
